on:
  push:
    branches:
      - main
name: 🚀 Deploy vue-template.maxmind.ma ON PUSH
jobs:
  web-deploy:
    name: 🎉 Deploy VUE LOGIN TEMPLATE TEST
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files TO SERVER
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.TEMPLATE_TEST_HOST }}
        username: ${{ secrets.TEMPLATE_TEST_FTP_USERNAME }}
        password: ${{ secrets.TEMPLATE_TEST_PASS }}
        exclude: .git*
          - .git*/**
          - node_modules/**
          - node_modules/**/*
          - **/.ENV
          - **/.env
          - .DS_Store
          - error_log
          - DB/**
          - **/var/**
          - **/vendor/**
          - .htaccess
          - .user.ini
          - **/error_log
          - *.zip
          - **_old
